### ISSUE TITLE
Discord issue

### ISSUE THREAD

**Issue by zbear2246** [bridge-core/bridge-jam#1]
What if you were banned from the discord server even tho you didn't know what was going on?

**Comment by outercloudstudio** [comment]
Why were you banned from the discord server?

**Comment by zbear2246** [comment]
The reason was spamming

**Comment by outercloudstudio** [comment]
I'll ask the other mods and see what they say.

**Comment by zbear2246** [comment]
I saw two other people spamming and I went to the # (insert room name) to ask them to stop and then It looked like my messages were getting deleted when 2 other people were spamming so I kept typing and I got banned.

**Comment by zbear2246** [comment]
what did they say? if you are done talking

**Comment by solvedDev** [comment]
What‘s your Discord account name?

**Comment by zbear2246** [comment]
Zachariah ^w^✾#9995

**Comment by zbear2246** [comment]
i have changed it

**Comment by zbear2246** [comment]
since the ban

**Comment by zbear2246** [comment]
@solvedDev

**Comment by zbear2246** [comment]
I'm not going to partisapate in the bridge-jam because i am still a begginner at this so i won't make a addon in a couple hours. baced on the theme.

**Comment by zbear2246** [comment]
also in the axe preset you need to change the parent: "itemGroup.name.pickaxe" to parent: "itemGroup.name.axe"

**Comment by zbear2246** [comment]
> What‘s your Discord account name?

hello

**Comment by zbear2246** [comment]
so

**Comment by zbear2246** [comment]
pls answer
it has been a couple of days.

**Comment by FrederoxDev** [comment]
I’m leaving a comment here because earlier in the thread you mentioned you changed your name. It could help if you were to send your [User ID](https://support.discord.com/hc/en-us/articles/206346498-Where-can-I-find-my-User-Server-Message-ID-) so the bridge team can check the logs for your old username

*(I am not a moderator on the bridge team, but used to be)*

**Comment by zbear2246** [comment]
<@579770111049728000>
there you go

**Comment by solvedDev** [comment]
I am not willing to unban you because you lied about why you were banned. This was definitely not a mistake, you were banned because you've spammed. I just looked up your nonsense, long message again
![Parts of the spam message](https://user-images.githubusercontent.com/33347616/174342385-94a0d7d1-a2f7-4c25-b190-f29f3e77f330.png)

**Comment by zbear2246** [comment]
I forgot I copied something and sent it but it got deleted to me. sorry about that
but thanks anywhay.
